require: rubocop-rspec

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'Gemfile.lock'
    - 'bin/**'
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false